version: "3.9"

services:
  parking-api:
    build: .
    container_name: smart_parking_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./facility_report.txt:/app/facility_report.txt
    restart: unless-stopped
